title: Your Website Title 
description: >- 
  Your website description.
baseurl: "/" 
url: "your-github-pages-url.github.io" # Replace with your GitHub Pages URL
# Exclude from building
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/"]

# -------------------------------
# Dark Mode & Font
# -------------------------------
theme: minima
defaults:
  - scope:
      path: ""
    values:
      layout: default
      font: Courier New
      darkmode: true # Enable dark mode

# -------------------------------
# Navigation from Markdown Headers
# -------------------------------
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true # Enable automatic IDs for headers
  hard_wrap: false

plugins:
  - jekyll-toc

# Add a custom variable to track the TOC
toc:
  permalink: true