title: "My Personal Website"
description: "A personal website built with Jekyll"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Theme settings
theme: minima

# Enable dark mode
minima:
  skin: dark

# Font settings
sass:
  style: compressed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Navigation bar settings
nav:
  - title: "Home"
    url: "/"
  - title: "Section 1"
    url: "#section-1"
  - title: "Section 2"
    url: "#section-2"
  - title: "Section 3"
    url: "#section-3"

# Exclude these files from the site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
