title: "Your Website Title"
description: "A description of your website"
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site

theme: minima # Use the minima theme as a base; you can customize further

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true # This automatically generates IDs for headers

highlighter: rouge # To enable syntax highlighting

# Enable Dark Mode
minima:
  skin: dark

# Custom CSS to apply Courier New font and adjust the navbar
sass:
  style: compressed

plugins:
  - jekyll-toc # Table of Contents generator

# Table of Contents settings
toc:
  min_level: 2 # Include h2 headers (## in markdown)
  max_level: 2 # Limit to h2 headers
  no_back_to_top: true # Remove "back to top" link

# Additional CSS
sass:
  style: compressed
  custom_css: assets/css/custom.scss

# Exclude items from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional: Specify where your site's content lives (default is in '_posts')
# defaults:
#   - scope:
#       path: "" # empty string means all files
#     values:
#       layout: "default"

# Optional: Customize the HTML output (e.g., to add classes, IDs, etc.)
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"
